name: Minimal

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions"
      - name: Output Date
        run: echo "Current date is $(date)"
